"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_0**qbf8g_j0a@5)#mnwh&xdj4js3$5ei(8uq#w-)))-u87ne-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'tutor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:5173',
    'http://localhost:5173',
]

OLLAMA_API_URL = 'http://127.0.0.1:11434/api/generate'
OLLAMA_COMMAND = 'ollama'
OLLAMA_MODEL = 'llama3.1:8b-instruct-q4_K_M'
OLLAMA_TIMEOUT_SECONDS = 60
OLLAMA_STARTUP_TIMEOUT_SECONDS = 20
OLLAMA_MODEL_PULL_TIMEOUT_SECONDS = 900
# How long Ollama should keep the chat model resident in memory after a
# request finishes. Avoids the multi-second cold-load hang on subsequent
# chat sends. Accepts any Ollama keep_alive format (e.g. "30m", "-1" = forever).
OLLAMA_KEEP_ALIVE = '2h'
# Maximum time to wait between streamed chunks from Ollama before we consider
# the stream stalled and abort. Guards against generation stalling midway.
OLLAMA_STREAM_IDLE_TIMEOUT_SECONDS = 45
# Maximum wall-clock time for a single streamed generation. Guards against
# pathologically slow or runaway generations hanging the tutor.
OLLAMA_STREAM_TOTAL_TIMEOUT_SECONDS = 180
TUTOR_DEBUG_LOGS = True

# Embedding and vector store settings
OLLAMA_BASE_URL = 'http://localhost:11434'
OLLAMA_EMBED_MODEL = 'nomic-embed-text'
CHROMA_PERSIST_DIR = BASE_DIR / 'data' / 'chroma'
