# Generated by Django 6.0.4 on 2026-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('liberalism', 'Liberalism'), ('rep-democracy', 'Representative Democracy')], max_length=32)),
                ('quiz_type', models.CharField(choices=[('pre', 'Pre-Quiz'), ('post', 'Post-Quiz'), ('interpolated', 'Interpolated')], max_length=16)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=512)),
                ('option_b', models.CharField(max_length=512)),
                ('option_c', models.CharField(max_length=512)),
                ('option_d', models.CharField(max_length=512)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('rewatch_start', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic', 'quiz_type', 'order_index'],
            },
        ),
    ]
