# Generated by Django 6.0.4 on 2026-04-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='citations_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='question',
            name='related_interpolated_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='transcript_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
