# Generated by Django 6.0.4 on 2026-04-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_add_transcript_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(db_index=True, max_length=5, unique=True)),
                ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D')], max_length=1)),
                ('tutor_topic', models.CharField(blank=True, max_length=32)),
                ('pre_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('post_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_scaffold_score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterpolatedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('topic', models.CharField(max_length=32)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('correct', models.BooleanField()),
                ('used_hint', models.BooleanField(default=False)),
                ('rewatched', models.BooleanField(default=False)),
                ('scaffold_score_after', models.FloatField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpolated_attempts', to='tutor.participantsession')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
    ]
