# Generated by Django 6.0.4 on 2026-04-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_participant_session_and_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsession',
            name='post_score',
        ),
        migrations.RemoveField(
            model_name='participantsession',
            name='post_total',
        ),
        migrations.RemoveField(
            model_name='participantsession',
            name='pre_score',
        ),
        migrations.RemoveField(
            model_name='participantsession',
            name='pre_total',
        ),
        migrations.AddField(
            model_name='participantsession',
            name='lib_post_correct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='lib_post_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='lib_pre_correct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='lib_pre_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='rep_post_correct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='rep_post_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='rep_pre_correct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='rep_pre_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('tutor', 'Tutor')], max_length=8)),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tutor.participantsession')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
