# Generated by Django 6.0.4 on 2026-04-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_per_topic_scores_and_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_type',
            field=models.CharField(choices=[('pre', 'Pre/Post'), ('interpolated', 'Interpolated')], max_length=16),
        ),
    ]
