# Generated by Django 6.0.4 on 2026-04-25 19:47

from django.db import migrations


def delete_post_questions(apps, schema_editor):
    Question = apps.get_model('tutor', 'Question')
    Question.objects.filter(quiz_type='post').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_remove_post_quiz_type'),
    ]

    operations = [
        migrations.RunPython(delete_post_questions, migrations.RunPython.noop),
    ]
