# Generated by Django 6.0.4 on 2026-04-25 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_delete_post_quiz_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_sheet', models.BooleanField()),
                ('over_18', models.BooleanField()),
                ('stem_student', models.BooleanField()),
                ('consent_form', models.BooleanField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='tutor.participantsession')),
            ],
        ),
    ]
