# Generated by Django 6.0.4 on 2026-04-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_add_consent_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrecord',
            name='post_session_questionnaire',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
